services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
    container_name: server
    expose:
      - 8000
    volumes:
      - static-volume:/app/server/static
    env_file:
      - .env

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - static-volume:/usr/share/nginx/html/static
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  static-volume:
