# Generated by Django 5.0.2 on 2024-02-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mqtt", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="data",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveField(
            model_name="data",
            name="relay",
        ),
        migrations.CreateModel(
            name="Relay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="mqtt_relay_timesta_b48038_idx"
                    )
                ],
            },
        ),
    ]
