# Generated by Django 5.0.2 on 2024-02-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mqtt", "0002_alter_data_options_remove_data_relay_relay"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relay",
            options={"get_latest_by": "timestamp"},
        ),
    ]
